### ISSUE TITLE
Realização do trabalho escrito

### ISSUE THREAD

**Issue by GiovannyCordeiro** [GiovannyCordeiro/projetosfaculdade#8]
Status de quem já realizou o trabalho escrito.

- [x] Parte Giovanny
- [x] Parte Bianca
- [x] Parte Viviane
- [x] Parte Rayana
- [x] Parte Fernanda
- [x] Parte Lucas

Coloque as suas respectivas partes nos comentários, por favor.

**Comment by GiovannyCordeiro** [comment]
## Texto

O TCC tem sua estrutura definida por elementos, que por sua vez são divididos em: Elementos pré-textuais, textuais e pós-textuais.

Os elementos pre-textuais são aqueles que antecedem o texto principal desenvolvido, alguns exemplos de elementos pre-textuais em um TCC são: Título e subtítulos, nome do autor, resumo na língua vernácula, palavras-chaves na língua vernácula.

Já os elementos textuais são justamente os quais desenvolvem o tema desenvolvido, ou seja, o texto principal. Os exemplos de elementos textuais em um TCC são: Introdução, desenvolvimento e conclusão.

Os elementos pós textuais servem de forma complementar ao TCC, de forma que desenvolvam mais contexto sobre o trabalho elaborado. Os exemplos de elementos textuais em um TCC são: Referências, glossário, apêndices e anexos.

Esses elementos seguem as normas da ABNT com objetivo de garantir a qualidade e compreensão da produção intelectual desenvolvida, por meio dela é possível ter uma padronização clara e objetiva na produção de trabalhos científicos, tecnológicos e documentais.

Vale observar que certos itens no desenvolvimento de um TCC são obrigatórios pela ABNT e outros não, apresentando caráter opcional.

Exemplos de itens obrigatórios: Capa, Folha de rosto, Folha de aprovação, Resumo na língua vernácula, resumo em língua estrangeira, Sumário, introdução, desenvolvimento, conclusão, referências.

Exemplos de itens opcionais: Lombada, errata, dedicatória, dedicatória, agradecimentos, epígrafe, lista de ilustrações, lista de tabelas, lista de abreviaturas e siglas, lista de símbolos, glossário, apêndice, anexo e índice.

## Referências

https://propesq.ufsc.br/para-que-serve-a-abnt-propesq-explica-05/
https://www.faneesp.edu.br/conteudo/ManualdoTCCINESUL.doc
https://www.todamateria.com.br/elementos-pre-textuais-em-trabalhos-academicos/

**Comment by BiacaKeyllaaa** [comment]
Definição

O trabalho de conclusão de curso (TCC) é uma exigência realizada no âmbito acadêmico para que o estudante consiga receber o seu diploma em um curso superior, esse tipo de trabalho também já está sendo adotado em algumas instituições de ensino fundamental e médio e em cursos de pós-graduação e cursos técnicos. 
Basicamente é um trabalho de caráter científico apresentado ao final do curso contendo um documento escrito e uma apresentação oral que será julgada por uma banca avaliadora. Esse trabalho deve seguir as normas ABNT - Associação Brasileira de Normas Técnicas  contendo em sua estrutura introdução, metodologia, desenvolvimento, conclusão e as fontes de pesquisa, deve ser construído em cima de uma problemática apresentando ao final uma possível solução. O conteúdo do trabalho diz respeito a um tema que englobe conhecimentos adquiridos por meio da formação do discente que através do TCC irá provar que está preparado, com base no seu olhar científico, para  atuar na área de estudo.
Todo esse processo é construído pelo acadêmico com a ajudar de um orientador, que será escolhido pelo próprio aluno, para auxiliar nas atividades por meio de avaliações e sugestões de melhorias. Esse orientar é escolhido dentre o corpo docente do curso realizado. Ainda sobre algumas particularidades do Trabalho de Conclusão de Curso, o mesmo ainda pode ser realizado de forma individual ou até mesmo em grupo, esses critérios são estabelecidos por cada instituição e coordenação de curso.
O TCC é uma importante etapa no aprendizado do aluno já que com ele vai ser colocado em prática todo o conhecimento adquirido nos anos de curso.

Referências:

PraValer, TCC: Guia completo com tudo que você precisa saber, 2023. Disponível em: https://www.pravaler.com.br/blog/dicas-de-estudo/tcc-guia-completo-com-tudo-que-voce-precisa-saber/ Acesso em: 21 de Out. de 2023

Terra, O que é TCC? Tudo sobre o Trabalho de Conclusão de Curso ,2023. Disponível em: https://www.terra.com.br/noticias/educacao/o-que-e-tcc-tudo-sobre-o-trabalho-de-conclusao-de-curso,ac1a842b04bd52d44604e78408c49a7ab8uku2xs.html Acesso em 21 de Out. 2023

RevistaCientifica, O que é um TCC - Trabalho de Conclusão de Curso - Revista Científica Núcleo do Conhecimento. YouTube, 3 de jan. de 2019. Disponível em: https://youtu.be/3UphFl6r1Rc?si=Dus4b45hNnAK-y8V Acesso em: 21 de Out. de 2023

FONTENELLE, André, O que é TCC? Como fazer um TCC passo a passo: o que significa TCC?. YouTube, 25 de jul. de 2017. Disponível em: https://youtu.be/OSXmWiZVT0g?si=55yxx1QFMxYsQmHG Acesso em: 21 de Out. 2023

TCC SEM DRAMA, O que é o TCC? | TCC Sem Drama. YouTube, 11 de fev. de 2021. Disponível em: https://youtu.be/StQppXpBvXk?si=2CSGPo4WmeamP-AI Acesso em: 21 de Out. 2023

**Comment by fernandaellenb** [comment]
**Tipos de TCC**
Artigo científico: Um artigo científico é um documento acadêmico que relata os resultados de uma pesquisa original ou estudo em um campo específico do conhecimento. Para abordar um tema específico de pesquisa, é necessário basear-se em conceitos, ideias, valores e teorias que possam fundamentar a argumentação de forma teoricamente consistente. A escrita de um artigo científico requer uma investigação minuciosa, com a utilização de dados e informações confiáveis. Em suma, a expressão 'artigo científico' se refere a uma forma de produção textual que comunica os resultados de uma investigação científica; ela se concentra em uma questão científica particular dentro de um campo específico, e é imprescindível que apresente resultados que sejam válidos e confiáveis.

Projeto Prático: Um projeto prático, em um contexto acadêmico, é uma tarefa que envolve a aplicação de conhecimentos teóricos para resolver problemas do mundo real ou criar algo concreto. Esses projetos têm como propósito permitir aos alunos a oportunidade de colocar em prática o conhecimento teórico adquirido, desenvolvendo habilidades concretas e demonstrando sua capacidade de resolver problemas de maneira efetiva. Alguns exemplos seriam, o desenvolvimento de um aplicativo de software, construção de um protótipo de engenharia, realização de um estudo de campo em uma comunidade entre outros. 

Tanto artigos científicos quanto projetos práticos desempenham papéis importantes na formação acadêmica, mas tem abordagens e objetivos diferentes. Enquanto os artigos científicos visam a pesquisa e a comunicação de resultados científicos, os projetos práticos têm foco na aplicação do conhecimento em situações reais ou a criação de produtos concretos.

**Referências**
ANPG, TCC: O que é, como fazer um!, 2022. Disponível em: https://www.anpg.org.br/2022/04/tcc-o-que-e-como-fazer-um/#:~:text=TCC%20de%20Projeto%20Pr%C3%A1tico,teoria%2C%20como%20fotografia%20e%20jornalismo. Acesso em 24 de Out. de 2023

RevistaCientífica, O que é um Artigo Científico? - Revista Científica Multidisciplinar Núcleo do Conhecimento. YouTube 27 de Abr. de 2019. Disponível em: https://www.youtube.com/watch?v=Vy_--9hWcg0&t=134s&ab_channel=RevistaCient%C3%ADficaN%C3%BAcleodoConhecimento Acesso em: 24 de Out. de 2023

PraValer, TCC: Guia completo com tudo que você precisa saber, 2023. Disponível em: https://www.pravaler.com.br/blog/dicas-de-estudo/tcc-guia-completo-com-tudo-que-voce-precisa-saber/ Acesso em: 24 de Out. de 2023

**Comment by lucasm-1002** [comment]
Tipos de TCC, Monografia. 

O Termo monografia deriva da junção das palavras gregas monos e graphein que se traduzem respectivamente como “um só” e “escrita”, gerando assim o significado de “uma única escrita”. Esse tipo de trabalho é mais aprofundado e extenso quando comparado aos outros tipos de TCC, ele é comumente composto por 30 ou mais páginas apresar de a ABNT não impor nenhum limite referente a essa quantidade. Nele se discorre sobre apenas um tema ou assunto, reunindo através de pesquisa bibliográfica informações sobre o conhecimento científico de diferentes autores, análises e interpretações sobre a área abordada, a fim de agregar valor ao conhecimento acadêmico ou para sociedade como um todo. 

A mesma é descrita por Carvalho (2012, p.148) como “o resultado do estudo científico de um tema ou de uma questão mais específica sobre determinado assunto; vai sistematizar o resultado das leituras, observações, críticas e reflexões feitas pelo educando”. 

Além de seguir as normas ABNT é comum que cada instituição defina um modelo específico para as monografias, podendo também estabelecer um limite de páginas, tendo como objetivo uma melhor padronização já que esse gênero de escrita pode estendendo-se além dos trabalhos de conclusão de curso de uma graduação, sendo também adotado para trabalhos de tese e dissertação. 

 

MORETTI, Isabella. Monografia: o que é, estrutura e como fazer. Regras para TCC, 2022. Disponível em: https://regrasparatcc.com.br/formatos-de-trabalhos-academicos/monografia/. Acesso em: 22 out. 2023. 

MORETTI, Isabella. Quantas páginas deve ter um TCC?. Regras para TCC, 2019. Disponível em: https://regrasparatcc.com.br/primeiros-passos/quantas-paginas-deve-ter-um-tcc/. Acesso em: 24 out. 2023. 

FACULDADE BARRETOS. MANUAL DE REALIZAÇÃO DOS TRABALHOS DE CONCLUSÃO DE CURSO–TCC: Modalidade Monografia e Artigo Científico. Disponível em: https://faculdadebarretos.com.br/wp-content/uploads/2018/11/Manual-TCC-2018-Administracao-Versao-Final.pdf. Acesso em: 24 out. 2023.

**Comment by Rayanak17** [comment]
Características de um TCC
Um TCC possui muitas características especificas para sua fundamentação, as principais são:

•	Título e tema: O título é a primeira coisa vista pelo leitor, portanto ele precisa transmitir o objetivo do TCC e deve contribuir com uma forma nova de conhecimento, transmitindo originalidade. Também deve abordar um tema relevante.

•	Estrutura: Geralmente, o TCC segue uma estrutura que inclui elementos pré-textuais, textuais e pós-textuais. Deve ser considerado os requisitos de extensão estabelecidos pela instituição.

•	Normas de formatação: Habitualmente, as instituições seguem diretrizes específicas de formatação.

•	Pesquisa e metodologia: É previsto que o autor realize uma pesquisa extensa e descreva como ela foi realizada, mostrando coleta de dados, instrumentos de pesquisa e análise de dados.

•	Coerência: O TCC deve ser escrito com clareza e consistência, possuindo organização lógica.

•	Análise e discussão: Apresentar os resultados da pesquisa de forma clara, interpretá-los, e responder questões da pesquisa.

•	Conclusão: Resumir pontos principais do TCC, mostrar descobertas, implicações e limitações.

•	Referências: Possui uma lista de todas as fontes usadas ao longo do trabalho.

GUIA DA MONOGRAFIA. As 11 características de um TCC excelente. Youtube, 15 de jan. de 2021. Disponível em: https://youtu.be/52B1JHLitgI?si=FapQUR2aUA5jP4wc. Acesso em: 24 de Out. de 2023.

 Aluno Expert. Monografia TCC: entenda tudo de sua Pesquisa. Disponível em: https://alunoexpert.com.br/monografia-tcc/#:~:text=Caracter%C3%ADsticas%20do%20TCC%20(Trabalho%20de,de%2040%20a%2070%20p%C3%A1ginas. Acesso: em 24 de Out. de 2023.

 Guia da monografia. As 11 características de um TCC excelente. Disponível em: https://guiadamonografia.com.br/11-caracteristicas-de-um-tcc-excelente/. Acesso em: 24 de Out. de 2023.

**Comment by GiovannyCordeiro** [comment]
## Parte da Vivi

É comum a muitos estudantes, ao terem a tarefa de elaborar um Trabalho de Conclusão de Curso(TCC), sentirem-se hesitantes ou amedrontados com tal desafio, principalmente, pelo pouco entendimento de planejar e executar esse tipo de documento acadêmico que muitas vezes é desconhecido ou não facilmente visualizado durante o processo. Nesse sentido, diante de uma perspectiva fundamental, o TCC nasce do objeto e necessidade de entender, organizar e transmitir o saber e entendimento para terceiros. Por tais razões, afirma-se que, qualquer boa ideia, se não estruturada de uma forma adequada e sistemática, corre o risco de ser confusa, mal interpretada ou até mesmo, nem chegue a ser compreendida.
Sendo assim, ao buscar um documento para servir de referência, buscamos por algo simples, estruturado e objetivo, com sinalizações claras de como um TCC deveria ser. O objetivo da exemplificação é despertar de forma fácil e didática, o que um projeto de conclusão deve ter. Abaixo, será discorrido sobre alguns pontos do modelo escolhido como referência:

1- O documento possui boa formação estrutural e apresenta pré-textuais imprescindível para o texto, tais como: a capa e a folha de rosto.  Ambas possuem o intuito de trazer reconhecimento ao autor do projeto, além de credibilidade a leitura com a validação da banca examinadora, apresenta informações sobre o curso do autor, instituição de ensino, data e local da produção do texto. Tais fatores não trazem apenas um ar mais sério ao trabalho, como também facilitam a pesquisa de outros estudantes no futuro, estes que também conseguirão pesquisar pelo TCC com o auxílio do título, subtítulo e entre outros -apontados como presentes no modelo;

2- Reserva uma área para agradecimentos de elaboração e conclusão do projeto. Essa parte é muito importante, já que nenhum conhecimento nasce do nada, ainda mais na sociedade humana, que está sempre a derivar os seus conhecimentos de outros pré-existentes;

3- Apresenta itens necessários para construir uma pré-ideia acerca do que será apresentado na seção textual do TCC, usando-se, para isso, do Resumo e da palavras-chave. Como geralmente os escritos do projeto de conclusão são longos, os resumos e as palavras-chave servem para sintetizar os principais assuntos do documento, facilitando também buscas futuras por aquele tipo de assunto do projeto de conclusão para terceiros;

4- Indicação clara e organizada das disposições das fotos e capítulos. Fazendo uso do sumário, o modelo facilita a pesquisa de quem quer ver algo mais específico, precisando apenas localizar, por meio do sumário, em qual página se encontra o capítulo 3, por exemplo, e se dirigir a ele para fazer a leitura. Ademais a isso, também é possível ver uma página destinada a explicar o significado das siglas do documento, o que é um ponto bem colocado, porque evita que o leitor tenha que buscar o significado de uma sigla por outro meio, poupando-lhe tempo e esforço;   

5- A estrutura do Desenvolvimento é formada por capítulos e subcapítulos, o que torna mais suscetível a construção dos argumentos de forma didática, progressiva e bem planejada; 

6- O final do modelo do TCC é completo. Ele não só permite concluir o desenvolvimento, como também possibilita o apontamento do estudante acerca do objetivo do trabalho(se foi alcançado ou não), como também trás espaço para as referências, 

7- Por fim, além de todos os fatores citados acima, um outro importante é que o trabalho já existe nítido para o aluno sob quais normas da ABNT o modelo se estrutura. Em cada página é possível ver as partes vermelhas, ou outras indicações, que destacam esse direcionamento.
